Housekeeping tasks
sanger/unified_warehouse pull request #219
Opened 2021-04-14 19:05 UTC by pjvv

Closes #

Changes proposed in this pull request:

*
*
* ...

2021-05-25 12:39 UTC, harrietc52 requested changes
Few v minor comments

2021-05-25 12:39 UTC, harrietc52 commented on README.md
> +This project provides with the view `cherrypicked_samples` that links data with
```suggestion
This project provides the view `cherrypicked_samples` that links data with
```

2021-05-25 12:39 UTC, harrietc52 commented on README.md
> +Integration Tests setup section at <https://github.com/sanger/event_warehouse/>)
```suggestion
Integration Tests setup section at <https://github.com/sanger/event_warehouse/#integration-tests-setup>)
```

2021-05-25 12:39 UTC, harrietc52 commented on README.md
>  4. Run the integration tests:
Don't think this is indented properly as code

2021-05-26 09:43 UTC, pjvv commented on README.md
>     bundle exec rspec --tag integration
```suggestion
        bundle exec rspec --tag integration
```

2021-05-26 09:44 UTC, merged